### ISSUE TITLE
covidDash.sql

### ISSUE THREAD

**Issue by yashodhank** [sachink23/c19-dashboard#1]
due to following error while importing
```
ERROR 1273 (HY000) at line 30: Unknown collation: 'utf8mb4_0900_ai_ci'
```

I have replaced it with to following:
```
utf8mb4_unicode_ci
```

Now it works and database is imported now.

**Comment by sachink23** [comment]
Thanks for informing, will take care of it while exporting db.

**Comment by sachink23** [comment]
Please delete **hospital_code** column from **hospital_master** table

**Comment by yashodhank** [comment]
You have not change collation to `utf8mb4_unicode_ci`
please update sql file and it will automatically get imporated only once.

**Comment by yashodhank** [comment]
Ignore earlier comment, I have imported updated sql now.
